[build]
  base = "barbearia-frontend"
  command = "npm run build"
  publish = "barbearia-frontend/dist" # <-- Mude de 'build' para 'dist'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200